name = "gastro"
main = ".open-next/worker.js"
compatibility_date = "2026-08-14"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "gastrointensivismo.com.br", custom_domain = true },
  { pattern = "www.gastrointensivismo.com.br", custom_domain = true }
]


[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "gastro-db"
database_id = "d3a6deb3-def1-4ac7-9826-8e1ed1f7e721"
